# Generated by Django 5.2 on 2025-05-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_dog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
